TheAddress.WebAdmin/Controllers/DistrictsController.cs
using Microsoft.AspNetCore.Mvc;
using TheAddress.BLL.Services.Interfaces;
using TheAddress.DAL.DBModel;
using TheAddress.DAL.Dtos;

namespace TheAddress.WebAdmin.Controllers
{
    public class DistrictsController : Controller
    {
        private readonly IGenericService<DistrictDto, District> _service;
        private readonly ILogger<DistrictsController> _logger;

        public DistrictsController(IGenericService<DistrictDto, District> service, ILogger<DistrictsController> logger)
        {
            _service = service;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var districts = await _service.GetListAsync();
            return View(districts);
        }

        public async Task<IActionResult> Update(int id)
        {
            var districts = await _service.GetByIdAsync(id);
            _logger.LogInformation($"Sistemdə {id} N-li Id məlumat çağrılmışdır");
            return View(districts);

        }

        [HttpPost]
        public IActionResult Update(DistrictDto itemDto)
        {
            var districts = _service.Update(itemDto);
            if (districts != null)
            {
                TempData["success"] = "Rayon uğurla dəyişdirildi.";
                _logger.LogInformation($"Sistemdə {itemDto.Id} N-li Id yenilənmişdir");
                return RedirectToAction("Index");
            }
            _logger.LogError($"Sistemdə olmayan {itemDto.Id} N-li Id çağrılmışdır");
            return View(districts);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var districts = await _service.GetByIdAsync(id);

            return View(districts);

        }
        [HttpPost]
        public IActionResult Delete(DistrictDto itemDto)
        {
            _service.Delete(itemDto.Id);
            TempData["success"] = "Rayon uğurla silindi.";
            return RedirectToAction("Index");


        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DistrictDto itemDto)
        {

            var districts = await _service.AddAsync(itemDto);
            if (districts != null)
            {
                TempData["success"] = "Rayon uğurla əlavə edildi.";
                _logger.LogError($"Sistemə {itemDto.Id} N-li Id yaradılmışdır");
                return RedirectToAction("Index");
            }
            return Ok(districts);
        }
    }
}

TheAddress.WebAdmin/Controllers/PropertiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheAddress.BLL.Services.Interfaces;
using TheAddress.DAL.Data;
using TheAddress.DAL.Dtos;

namespace TheAddress.WebAdmin.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly IPropertyService _service;
        private readonly AppDBContext db;
        [Obsolete]
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;
        private readonly ILogger<PropertiesController> _logger;

        [Obsolete]
        public PropertiesController(AppDBContext db, IPropertyService service, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment, ILogger<PropertiesController> logger)
        {
            _service = service;
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;
            this.db = db;
        }
        public async Task<IActionResult> Index()
        {
            //var properties = await _service.GetListAsync();
            return View(await db.Properties.Include(x => x.PropertyCategory).ToListAsync());
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.PropertyCategory = new SelectList(await _service.GetCategoriesAsync(), "Id", "Name");
            ViewBag.Region = new SelectList(db.Districts.ToList(), "Id", "Name");

            PropertyDto model = new()
            {
                PropertyCategoryDtos = await _service.GetCategoriesAsync()
            };
            return View(model);
        }
        [HttpPost]
        [Obsolete]
        public async Task<IActionResult> Create(PropertyDto itemDto, List<IFormFile> files)
        {
            ViewBag.PropertyCategory = new SelectList(await _service.GetCategoriesAsync(), "Id", "Name");
            ViewBag.Region = new SelectList(db.Districts.ToList(), "Id", "Name");
            if (ModelState.IsValid)
            {


                string wwwRootPath = _hostingEnvironment.WebRootPath;
                string folderPath = @"Documents\PropertyImages";
                string fullPath = Path.Combine(wwwRootPath, folderPath);
                itemDto.PropertyDocuments = new List<PropertyDocumentDto>();
                foreach (var file in files)
                {
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(file.FileName);
                    string realPath = Path.Combine(fullPath, fileName + extension);

                    using (var fileStream = new FileStream(realPath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    PropertyDocumentDto propertyDocument = new()
                    {
                        DocumentUrl = @"Documents/PropertyImages/" + fileName + extension,
                    };
                    itemDto.PropertyDocuments.Add(propertyDocument);

                }
                if (itemDto.PropertyDocuments.Count > 0)
                {
                    itemDto.ProfileDocPath = itemDto.PropertyDocuments[0].DocumentUrl;
                }

                await _service.AddAsync(itemDto);


                TempData["success"] = "Əmlak uğurla əlavə edildi";
                _logger.LogInformation($"Sistemə {itemDto.Id} N-li Id yaradılmışdır");

                return RedirectToAction("Index");
            }


            return View(itemDto);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            ViewBag.PropertyCategory = new SelectList(await _service.GetCategoriesAsync(), "Id", "Name");
            ViewBag.Region = new SelectList(db.Districts.ToList(), "Id", "Name");
            if (id == null)
            {
                _logger.LogError("Sıfır gəlidiyi üçün xəta baş verdi");
                return NotFound();

            }

            var property = await _service.GetByIdAsync(id.Value);
            //var propertyImage = db.PropertyDocuments.Where(p=>p.PropertyId == id).ToList();

            if (property == null)
            {
                _logger.LogError($"Sistemdə olmayan {id} N-li Id çağrılmışdır");
                return NotFound();
            }

            PropertyDto model = new()
            {
                Id = property.Id,
                Name = property.Name,
                Description = property.Description,
                Price = property.Price,
                Address = property.Address,
                RoomCount = property.RoomCount,
                Floor = property.Floor,
                Area = property.Area,
                PropertyCategoryId = property.PropertyCategoryId,
                PropertyCategoryDtos = await _service.GetCategoriesAsync(),
                DistrictId = property.DistrictId,
                DistrictDtos = property.DistrictDtos,
                Buy = property.Buy,
                Rent = property.Rent,
                Location = property.Location,
                PropertyDocuments = property.PropertyDocuments,
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Update(int id, PropertyDto itemDto, List<IFormFile> files)
        {
            ViewBag.PropertyCategory = new SelectList(await _service.GetCategoriesAsync(), "Id", "Name");
            ViewBag.Region = new SelectList(db.Districts.ToList(), "Id", "Name");
            //if (id != itemDto.Id)
            //{
            //    _logger.LogInformation($"Sistemdə olmayan {id} N-li Id çağrılmışdır");
            //    return NotFound();
            //}

            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostingEnvironment.WebRootPath;
                string folderPath = @"Documents\PropertyImages";
                string fullPath = Path.Combine(wwwRootPath, folderPath);

                itemDto.PropertyDocuments = itemDto.PropertyDocuments ?? new List<PropertyDocumentDto>();

                foreach (var file in files)
                {
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(file.FileName);
                    string realPath = Path.Combine(fullPath, fileName + extension);

                    using (var fileStream = new FileStream(realPath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    PropertyDocumentDto productDocument = new()
                    {
                        DocumentUrl = @"Documents/PropertyImages/" + fileName + extension,
                    };

                    itemDto.PropertyDocuments.Add(productDocument);
                }

                if (itemDto.PropertyDocuments.Count > 0)
                {
                    itemDto.ProfileDocPath = itemDto.PropertyDocuments[0].DocumentUrl;
                }

                _service.UpdateProperty(itemDto);

                TempData["success"] = "Əmlak uğurla dəyişdirildi";
                _logger.LogInformation($"Sistemdə {id} N-li Id  yenilənmişdir");
                return RedirectToAction("Index");
            }

            return View(itemDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var property = await _service.GetByIdAsync(id);

            return View(property);

        }
        [HttpPost]
        public IActionResult Delete(PropertyDto itemDto)
        {
            _service.Delete(itemDto.Id);
            TempData["success"] = "Əmlak uğurla silindi.";
            _logger.LogInformation($"Sistemdə {itemDto.Id} N-li Id silinmişdir");
            return RedirectToAction("Index");

        }
    }
}

TheAddress.WebAdmin/Controllers/PropertyCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using TheAddress.BLL.Services.Interfaces;
using TheAddress.DAL.DBModel;
using TheAddress.DAL.Dtos;

namespace TheAddress.WebAdmin.Controllers
{
    public class PropertyCategoriesController : Controller
    {
        private readonly IGenericService<PropertyCategoryDto, PropertyCategory> _service;
        private readonly ILogger<PropertyCategoriesController> _logger;

        public PropertyCategoriesController(IGenericService<PropertyCategoryDto, PropertyCategory> service, ILogger<PropertyCategoriesController> logger)
        {
            _service = service;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _service.GetListAsync();
            return View(categories);
        }

        public async Task<IActionResult> Update(int id)
        {
            var category = await _service.GetByIdAsync(id);
            _logger.LogInformation($"Sistemdə {id} N-li Id məlumat çağrılmışdır");
            return View(category);

        }

        [HttpPost]
        public IActionResult Update(PropertyCategoryDto itemDto)
        {
            var category = _service.Update(itemDto);
            if (category != null)
            {
                TempData["success"] = "Kateqoriya uğurla dəyişdirildi.";
                _logger.LogInformation($"Sistemdə {itemDto.Id} N-li Id yenilənmişdir");
                return RedirectToAction("Index");
            }
            _logger.LogError($"Sistemdə olmayan {itemDto.Id} N-li Id çağrılmışdır");
            return View(category);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var category = await _service.GetByIdAsync(id);

            return View(category);

        }
        [HttpPost]
        public IActionResult Delete(PropertyCategoryDto itemDto)
        {
            _service.Delete(itemDto.Id);
            TempData["success"] = "Kateqoriya uğurla silindi.";
            return RedirectToAction("Index");


        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PropertyCategoryDto itemDto)
        {

            var category = await _service.AddAsync(itemDto);
            if (category != null)
            {
                TempData["success"] = "Kateqoriya uğurla əlavə edildi.";
                _logger.LogError($"Sistemə {itemDto.Id} N-li Id yaradılmışdır");
                return RedirectToAction("Index");
            }
            return Ok(category);
        }
    }
}

TheAddress.WebAdmin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Login Boxed | CORK - Multipurpose Bootstrap Dashboard Template</title>
    <link rel="icon" type="image/x-icon" href="~/assets/img/favicon.ico" />
    <link href="~/assets/css/loader.css" rel="stylesheet" type="text/css" />
    <script src="~/assets/js/loader.js"></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" href="~/css/site.css" />


    <link href="~/assets/css/authentication/form-2.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/forms/theme-checkbox-radio.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/forms/switches.css">

</head>
<body >

    @RenderBody()


    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="~/assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="~/bootstrap/js/popper.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/js/authentication/form-2.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

TheAddress.WebAdmin/Views/Shared/_Footer.cshtml
<div class="footer-wrapper">
    @*<div class="footer-section f-section-1">
        <p class="">Copyright © 2021 <a target="_blank" href="https://designreset.com">DesignReset</a>, All rights reserved</p>
    </div>
    <div class="footer-section f-section-2">
        <p class="">Coded with <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg></p>
    </div>*@
</div>

TheAddress.WebAdmin/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheAddress.WebAdmin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TheAddress.WebAdmin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TheAddress.WebAdmin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TheAddress.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - TheAddress.WebAdmin</title>
    <link rel="icon" type="image/x-icon" href="~/assets/img/favicon.ico" />
    <link href="~/assets/css/loader.css" rel="stylesheet" type="text/css" />
    <script src="~/assets/js/loader.js"></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link href="~/assets/css/plugins.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <link href="~/plugins/apex/apexcharts.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/dashboard/dash_1.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />



</head>
<body>
    <partial name="_Loader" />
    <partial name="_MainHeader" />
    <partial name="_SubHeader" />
    <div class="main-container" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>
        <partial name="_Sidebar" />
        <div id="content" class="main-content">
            <partial name="_Notification">
                @RenderBody()
                <partial name="_Footer" />
        </div>
    </div>



    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="~/assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="~/bootstrap/js/popper.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/app.js"></script>
    <script>
        $(document).ready(function () {
            App.init();
        });
    </script>
    <script src="~/assets/js/custom.js"></script>
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
    <script src="~/plugins/apex/apexcharts.min.js"></script>
    <script src="~/assets/js/dashboard/dash_1.js"></script>
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TheAddress.WebAdmin/Views/Shared/_Loader.cshtml
    <!-- BEGIN LOADER -->
<div id="load_screen">
    <div class="loader">
        <div class="loader-content">
            <div class="spinner-grow align-self-center"></div>
        </div>
    </div>
</div>
<!--  END LOADER -->

TheAddress.WebAdmin/Views/Shared/_MainHeader.cshtml
    <!--  BEGIN NAVBAR  -->
<div class="header-container fixed-top">
    <header class="header navbar navbar-expand-sm">

        <ul class="navbar-item theme-brand flex-row  text-center">
            <li class="nav-item theme-logo">
                <a href="index.html">
                    <img src="~/assets/img/logo.jpg" class="navbar-logo" alt="logo">
                </a>
            </li>
            <li class="nav-item theme-text">
                <a href="#" class="nav-link"> TheAddress Luxury Property </a>
            </li>
        </ul>

        <ul class="navbar-item flex-row ml-md-auto">

            <li class="nav-item dropdown user-profile-dropdown">
                <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <img src="~/assets/img/avatar.jpg" alt="avatar">
                </a>
                <div class="dropdown-menu position-absolute" aria-labelledby="userProfileDropdown">
                    <div class="">
                        <div class="dropdown-item">
                            <a  asp-controller="Home" asp-action="SignUp"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feath
                                    er feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 
                                    0 0 1 2-2h4"></path><polyline points="16 17 21 
                                    12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line> </svg> Sign Out</> </a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </header>
</div>
<!--  END NAVBAR  -->

TheAddress.WebAdmin/Views/Shared/_Sidebar.cshtml
   <!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">

    <nav id="sidebar">
        <div class="shadow-bottom"></div>
        <ul class="list-unstyled menu-categories" id="accordionExample">
            <li class="menu">
                <a href="#dashboard" data-active="true" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        <span>Home</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
            </li>

            <li class="menu">
                <a href="#app" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-cpu"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>
                        <span>İdarəetmə</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="app" data-parent="#accordionExample">
                    <li>
                        <a asp-area="" asp-controller="PropertyCategories" asp-action="Index">Əmlak kateqoriyası</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Districts" asp-action="Index">Rayonlar</a>
                    </li>
                    <li>

                        <a asp-area="" asp-controller="Properties" asp-action="Index">Əmlaklar</a>
                    </li>
                </ul>
            </li>


            <li class="menu">
                <a href="#users" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                        <span>Users Management</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="users" data-parent="#accordionExample">
                    <li>
                        <a asp-area="" asp-controller="UserManagment" asp-action="UserIndex">İstifadəçilər</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="UserManagment" asp-action="RoleIndex">Rollar</a>
                    </li>
                </ul>
            </li>

           
            <li class="menu">
                <a target="_blank" href="../../documentation/index.html" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>
                        <span>Documentation</span>
                    </div>
                </a>
            </li>

        </ul>

    </nav>

</div>
<!--  END SIDEBAR  -->